name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Esegui ogni giorno a mezzanotte
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist folder
        run: mkdir -p dist

      # Genera l'animazione Snake
      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      # Verifica che i file siano stati generati correttamente
      - name: Ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
